import os

class Settings:
    API_ID = os.getenv("API_ID1", "")
    API_HASH = os.getenv("API_HASH1", "")

    MIN_AVAILABLE_ENERGY = 200
    SLEEP_BY_MIN_ENERGY = [1800, 3600]

    AUTO_UPGRADE = True
    MAX_LEVEL = 10
    MIN_PROFIT = 300
    MAX_PRICE = 50000000

    BALANCE_TO_SAVE = 1000000
    UPGRADES_COUNT = 20

    MAX_COMBO_PRICE = 10000000

    APPLY_COMBO = True
    APPLY_PROMO_CODES = False
    APPLY_DAILY_CIPHER = True
    APPLY_DAILY_REWARD = True
    APPLY_DAILY_ENERGY = True
    APPLY_DAILY_MINI_GAME = True

    SLEEP_MINI_GAME_TILES = [600, 900]
    SCORE_MINI_GAME_TILES = [300, 500]
    GAMES_COUNT = [1, 1]

    AUTO_COMPLETE_TASKS = True

    USE_TAPS = True
    RANDOM_TAPS_COUNT = [10, 50]
    SLEEP_BETWEEN_TAP = [10, 25]

    USE_RANDOM_DELAY_IN_RUN = False
    RANDOM_DELAY_IN_RUN = [0, 15]

    USE_RANDOM_USERAGENT = False

settings = Settings() 
